"""updated schema

Revision ID: 5706f8dfd92b
Revises: c94919aeecd5
Create Date: 2025-08-11 06:29:49.276375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5706f8dfd92b'
down_revision: Union[str, Sequence[str], None] = 'c94919aeecd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_address', sa.String(length=320), nullable=True),
    sa.Column('to_addresses', sa.Text(), nullable=True),
    sa.Column('cc_addresses', sa.Text(), nullable=True),
    sa.Column('bcc_addresses', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_date', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.String(length=1024), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('headers_json', sqlite.JSON(), nullable=True),
    sa.Column('raw_rfc822', sa.Text(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('size_estimate', sa.Integer(), nullable=True),
    sa.Column('links_json', sqlite.JSON(), nullable=True),
    sa.Column('sender_ip', sa.String(length=64), nullable=True),
    sa.Column('internal_metadata', sqlite.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_connection_id', 'provider_message_id', name='uq_mailbox_provider_msg')
    )
    op.create_index(op.f('ix_emails_mailbox_connection_id'), 'emails', ['mailbox_connection_id'], unique=False)
    op.create_index('ix_emails_mailbox_date', 'emails', ['mailbox_connection_id', 'date'], unique=False)
    op.create_index('ix_emails_status', 'emails', ['status'], unique=False)
    op.create_index(op.f('ix_emails_synced_at'), 'emails', ['synced_at'], unique=False)
    op.create_table('mailbox_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('provider_cursor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_sync_jobs_mailbox_connection_id'), 'mailbox_sync_jobs', ['mailbox_connection_id'], unique=False)
    op.create_table('email_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('indicators', sqlite.JSON(), nullable=True),
    sa.Column('shap_insights', sqlite.JSON(), nullable=True),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', name='uq_analysis_email')
    )
    op.create_index(op.f('ix_email_analysis_email_id'), 'email_analysis', ['email_id'], unique=False)
    op.create_index('ix_email_analysis_risk', 'email_analysis', ['risk_label'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('provider_attachment_id', sa.String(length=255), nullable=True),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_email_id'), 'email_attachments', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_attachments_email_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index('ix_email_analysis_risk', table_name='email_analysis')
    op.drop_index(op.f('ix_email_analysis_email_id'), table_name='email_analysis')
    op.drop_table('email_analysis')
    op.drop_index(op.f('ix_mailbox_sync_jobs_mailbox_connection_id'), table_name='mailbox_sync_jobs')
    op.drop_table('mailbox_sync_jobs')
    op.drop_index(op.f('ix_emails_synced_at'), table_name='emails')
    op.drop_index('ix_emails_status', table_name='emails')
    op.drop_index('ix_emails_mailbox_date', table_name='emails')
    op.drop_index(op.f('ix_emails_mailbox_connection_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
