"""Enforce unique user-email pair on mailbox connections

Revision ID: 89794d0123a2
Revises: 3d26e143c97c
Create Date: 2025-07-22 12:39:09.099147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89794d0123a2'
down_revision: Union[str, Sequence[str], None] = '3d26e143c97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_email', 'mailbox_connections', ['user_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'mailbox_connections', type_='unique')
    # ### end Alembic commands ###
