"""updated schema

Revision ID: ab8a74cfea30
Revises: 
Create Date: 2025-08-21 13:40:45.313879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ab8a74cfea30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_user_email')
    )
    op.create_index(op.f('ix_mailbox_connections_email'), 'mailbox_connections', ['email'], unique=False)
    op.create_index(op.f('ix_mailbox_connections_user_id'), 'mailbox_connections', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('reset_code_expires', sa.DateTime(), nullable=True),
    sa.Column('notify_email_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_policy_enabled', sa.Boolean(), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agent_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_emails_processed', sa.Integer(), nullable=True),
    sa.Column('total_deep_scans', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.Integer(), nullable=True),
    sa.Column('active_policies_triggered', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_stats_id'), 'agent_stats', ['id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_address', sa.String(length=320), nullable=True),
    sa.Column('to_addresses', sa.Text(), nullable=True),
    sa.Column('cc_addresses', sa.Text(), nullable=True),
    sa.Column('bcc_addresses', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_date', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.String(length=1024), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('headers_json', sqlite.JSON(), nullable=True),
    sa.Column('raw_rfc822', sa.Text(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('size_estimate', sa.Integer(), nullable=True),
    sa.Column('links_json', sqlite.JSON(), nullable=True),
    sa.Column('sender_ip', sa.String(length=64), nullable=True),
    sa.Column('internal_metadata', sqlite.JSON(), nullable=True),
    sa.Column('user_marked_safe', sa.Boolean(), nullable=False),
    sa.Column('user_override_note', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_connection_id', 'provider_message_id', name='uq_mailbox_provider_msg')
    )
    op.create_index(op.f('ix_emails_mailbox_connection_id'), 'emails', ['mailbox_connection_id'], unique=False)
    op.create_index('ix_emails_mailbox_date', 'emails', ['mailbox_connection_id', 'date'], unique=False)
    op.create_index('ix_emails_status', 'emails', ['status'], unique=False)
    op.create_index(op.f('ix_emails_synced_at'), 'emails', ['synced_at'], unique=False)
    op.create_table('mailbox_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', 'cancelled', name='scanstateenum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_mails_scanned', sa.Integer(), nullable=False),
    sa.Column('flagged_email_count', sa.Integer(), nullable=False),
    sa.Column('phishing_high', sa.Integer(), nullable=False),
    sa.Column('phishing_medium', sa.Integer(), nullable=False),
    sa.Column('phishing_low', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('provider_cursor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_sync_jobs_mailbox_connection_id'), 'mailbox_sync_jobs', ['mailbox_connection_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_table('email_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('indicators', sqlite.JSON(), nullable=True),
    sa.Column('shap_insights', sqlite.JSON(), nullable=True),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', name='uq_analysis_email')
    )
    op.create_index(op.f('ix_email_analysis_email_id'), 'email_analysis', ['email_id'], unique=False)
    op.create_index('ix_email_analysis_risk', 'email_analysis', ['risk_label'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('provider_attachment_id', sa.String(length=255), nullable=True),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_email_id'), 'email_attachments', ['email_id'], unique=False)
    op.create_table('email_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url_count', sa.Integer(), nullable=True),
    sa.Column('url_domains_json', sqlite.JSON(), nullable=True),
    sa.Column('url_tlds_json', sqlite.JSON(), nullable=True),
    sa.Column('url_obfuscation_hits', sa.Integer(), nullable=True),
    sa.Column('url_looks_like_login', sa.Boolean(), nullable=True),
    sa.Column('url_reputation', sa.String(length=16), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('attachment_exts_json', sqlite.JSON(), nullable=True),
    sa.Column('attachment_dangerous', sa.Boolean(), nullable=True),
    sa.Column('spf', sa.String(length=16), nullable=True),
    sa.Column('dkim', sa.String(length=16), nullable=True),
    sa.Column('dmarc', sa.String(length=16), nullable=True),
    sa.Column('reply_to_mismatch', sa.Boolean(), nullable=True),
    sa.Column('sender_ip', sa.String(length=64), nullable=True),
    sa.Column('sender_asn', sa.String(length=32), nullable=True),
    sa.Column('sender_geo', sa.String(length=64), nullable=True),
    sa.Column('lang_code', sa.String(length=8), nullable=True),
    sa.Column('lang_confidence', sa.Float(), nullable=True),
    sa.Column('suspicious_link', sa.Boolean(), nullable=True),
    sa.Column('suspicious_attachment', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('details_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_enrichments_created_at'), 'email_enrichments', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_enrichments_email_id'), 'email_enrichments', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_enrichments_run_id'), 'email_enrichments', ['run_id'], unique=False)
    op.create_table('email_scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='syncstate'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('last_log', sa.String(length=512), nullable=True),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scan_jobs_email_id'), 'email_scan_jobs', ['email_id'], unique=False)
    op.create_table('mailbox_shap_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_scan_id', sa.Integer(), nullable=False),
    sa.Column('insight_feature', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_scan_id'], ['mailbox_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailbox_shap_insights')
    op.drop_index(op.f('ix_email_scan_jobs_email_id'), table_name='email_scan_jobs')
    op.drop_table('email_scan_jobs')
    op.drop_index(op.f('ix_email_enrichments_run_id'), table_name='email_enrichments')
    op.drop_index(op.f('ix_email_enrichments_email_id'), table_name='email_enrichments')
    op.drop_index(op.f('ix_email_enrichments_created_at'), table_name='email_enrichments')
    op.drop_table('email_enrichments')
    op.drop_index(op.f('ix_email_attachments_email_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index('ix_email_analysis_risk', table_name='email_analysis')
    op.drop_index(op.f('ix_email_analysis_email_id'), table_name='email_analysis')
    op.drop_table('email_analysis')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_mailbox_sync_jobs_mailbox_connection_id'), table_name='mailbox_sync_jobs')
    op.drop_table('mailbox_sync_jobs')
    op.drop_table('mailbox_scans')
    op.drop_table('mailbox_activity_logs')
    op.drop_index(op.f('ix_emails_synced_at'), table_name='emails')
    op.drop_index('ix_emails_status', table_name='emails')
    op.drop_index('ix_emails_mailbox_date', table_name='emails')
    op.drop_index(op.f('ix_emails_mailbox_connection_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_agent_stats_id'), table_name='agent_stats')
    op.drop_table('agent_stats')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mailbox_connections_user_id'), table_name='mailbox_connections')
    op.drop_index(op.f('ix_mailbox_connections_email'), table_name='mailbox_connections')
    op.drop_table('mailbox_connections')
    # ### end Alembic commands ###
