"""initial schema

Revision ID: c2e7333c3876
Revises: 
Create Date: 2025-08-07 02:52:44.189358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e7333c3876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_user_email')
    )
    op.create_index(op.f('ix_mailbox_connections_email'), 'mailbox_connections', ['email'], unique=False)
    op.create_index(op.f('ix_mailbox_connections_user_id'), 'mailbox_connections', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('reset_code_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('mailbox_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_scan_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('total_mails_scanned', sa.Integer(), nullable=False),
    sa.Column('flagged_email_count', sa.Integer(), nullable=False),
    sa.Column('phishing_high', sa.Integer(), nullable=False),
    sa.Column('phishing_medium', sa.Integer(), nullable=False),
    sa.Column('phishing_low', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_shap_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_summary_id', sa.Integer(), nullable=False),
    sa.Column('insight_feature', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['scan_summary_id'], ['mailbox_scan_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailbox_shap_insights')
    op.drop_table('mailbox_scan_summaries')
    op.drop_table('mailbox_activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mailbox_connections_user_id'), table_name='mailbox_connections')
    op.drop_index(op.f('ix_mailbox_connections_email'), table_name='mailbox_connections')
    op.drop_table('mailbox_connections')
    # ### end Alembic commands ###
